$(document).ready(function () {

	/*****Fixed Menu******/
	var secondaryNav = $('.cd-secondary-nav'),
		secondaryNavTopPosition = secondaryNav.offset().top;
	$(window).on('scroll', function () {
		var navbar_height = document.querySelector('.navbar').offsetHeight;
		var top = 30;
		if ($(window).scrollTop() > secondaryNavTopPosition) {
			secondaryNav.addClass('is-fixed');
			$("body").css("padding-top", navbar_height);
		} else {
			secondaryNav.removeClass('is-fixed');
			$("body").css("padding-top", 0);
		}
	});

});
// Generated by CoffeeScript 1.7.1
$(document).ready(function () {
	$(".carousel").carousel({
		interval: 2000
	});
	$(".carousel").on("slid", function () {
		var to_slide;
		to_slide = $(".carousel-item.active").attr("data-slide-no");
		$(".myCarousel-target.active").removeClass("active");
		$(".carousel-indicators [data-slide-to=" + to_slide + "]").addClass("active");
	});
	$(".myCarousel-target").on("click", function () {
		$(this).preventDefault();
		$(".carousel").carousel(parseInt($(this).attr("data-slide-to")));
		$(".myCarousel-target.active").removeClass("active");
		$(this).addClass("active");
	});
});